name: SEO QA Check

on:
  push:
    branches: [ main, seo/* ]
  pull_request:
    branches: [ main ]

jobs:
  seo-qa:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run URL QA Check
      run: |
        node scripts/qa-url-check.js

    - name: Validate Sitemap XML
      run: |
        xmllint --noout sitemap.xml || (echo "❌ Invalid sitemap.xml format" && exit 1)
        echo "✅ sitemap.xml is valid XML"

    - name: Check robots.txt
      run: |
        if [ -f robots.txt ]; then
          echo "✅ robots.txt exists"
          grep -q "Sitemap: https://nextsteptherapy.ca/sitemap.xml" robots.txt || (echo "❌ robots.txt missing sitemap reference" && exit 1)
          echo "✅ robots.txt contains sitemap reference"
        else
          echo "❌ robots.txt not found" && exit 1
        fi

    - name: Check canonical consistency
      run: |
        # Check for www in canonical tags
        if grep -r 'rel="canonical".*www\.' *.html; then
          echo "❌ Found www in canonical URLs"
          exit 1
        else
          echo "✅ No www found in canonical URLs"
        fi

        # Check for .html in canonical tags
        if grep -r 'rel="canonical".*\.html' *.html; then
          echo "❌ Found .html extensions in canonical URLs"
          exit 1
        else
          echo "✅ No .html extensions in canonical URLs"
        fi

    - name: Upload QA Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: qa-results
        path: qa-results.json